<a href="https://colab.research.google.com/github/partha2412/Time-Series-Forecast/blob/main/TimeSeries_forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
tdf = pd.read_parquet("/content/drive/MyDrive/DBA/Project/demand_forecasting_training.parquet")
tdf.head()

  Store_ID    SKU_ID       Month  Sales Category BaselineForecast
0      S01  SKU_0483  2022-06-01      4        C              0.6
1      S01  SKU_0591  2022-06-01    198        C              0.0
2      S01  SKU_0855  2022-06-01   1366        B          2331.98
3      S01  SKU_1176  2022-06-01  71160        A         42525.27
4      S01  SKU_1378  2022-06-01      2        C             1.63

In [7]:
tdf.shape

(2945, 6)

In [8]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2945 entries, 0 to 2944
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Store_ID          2945 non-null   object
 1   SKU_ID            2945 non-null   object
 2   Month             2945 non-null   object
 3   Sales             2945 non-null   object
 4   Category          2945 non-null   object
 5   BaselineForecast  2945 non-null   object
dtypes: object(6)
memory usage: 225.6+ KB

In [9]:
tdf.dtypes

Store_ID            object
SKU_ID              object
Month               object
Sales               object
Category            object
BaselineForecast    object
dtype: object

In [10]:
vdf = pd.read_parquet("/content/drive/MyDrive/DBA/Project/demand_forecasting_validation.parquet")
vdf.head()

     Store_ID    SKU_ID       Month   Sales Category    BaselineForecast
2945      S01  SKU_0483  2025-01-01       0        C                0.63
2946      S01  SKU_0591  2025-01-01      24        C                9.69
2947      S01  SKU_0855  2025-01-01    1324        B   774.5699999999999
2948      S01  SKU_1176  2025-01-01  117246        A            46035.71
2949      S01  SKU_1378  2025-01-01       4        C  2.0700000000000003

In [11]:
vdf.shape

(475, 6)

In [12]:
vdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 475 entries, 2945 to 3419
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Store_ID          475 non-null    object
 1   SKU_ID            475 non-null    object
 2   Month             475 non-null    object
 3   Sales             475 non-null    object
 4   Category          475 non-null    object
 5   BaselineForecast  475 non-null    object
dtypes: object(6)
memory usage: 42.1+ KB

In [13]:
vdf.dtypes

Store_ID            object
SKU_ID              object
Month               object
Sales               object
Category            object
BaselineForecast    object
dtype: object

#preprocessing

typecasting

In [15]:
tdf.head()

  Store_ID    SKU_ID       Month  Sales Category BaselineForecast
0      S01  SKU_0483  2022-06-01      4        C              0.6
1      S01  SKU_0591  2022-06-01    198        C              0.0
2      S01  SKU_0855  2022-06-01   1366        B          2331.98
3      S01  SKU_1176  2022-06-01  71160        A         42525.27
4      S01  SKU_1378  2022-06-01      2        C             1.63

In [34]:
tdf['Sales'] = pd.to_numeric(tdf['Sales'], errors='coerce').fillna(0).astype('float64')
tdf['Category'] = tdf["Category"].astype('category')
tdf['Store_ID'] = tdf["Store_ID"].astype('str')
tdf['SKU_ID'] = tdf["SKU_ID"].astype('str')
tdf['Month'] = pd.to_datetime(tdf['Month'])

In [35]:
tdf.dtypes

Store_ID                    object
SKU_ID                      object
Month               datetime64[ns]
Sales                      float64
Category                  category
BaselineForecast            object
dtype: object

In [36]:
vdf.head()

     Store_ID    SKU_ID       Month   Sales Category    BaselineForecast
2945      S01  SKU_0483  2025-01-01       0        C                0.63
2946      S01  SKU_0591  2025-01-01      24        C                9.69
2947      S01  SKU_0855  2025-01-01    1324        B   774.5699999999999
2948      S01  SKU_1176  2025-01-01  117246        A            46035.71
2949      S01  SKU_1378  2025-01-01       4        C  2.0700000000000003

In [37]:
vdf['Sales'] = pd.to_numeric(vdf['Sales'], errors='coerce').fillna(0).astype('float64')
vdf['Category'] = vdf["Category"].astype('category')
vdf['Store_ID'] = vdf["Store_ID"].astype('str')
vdf['SKU_ID'] = vdf["SKU_ID"].astype('str')
vdf['Month'] = pd.to_datetime(vdf['Month'])

In [38]:
vdf.dtypes

Store_ID                    object
SKU_ID                      object
Month               datetime64[ns]
Sales                      float64
Category                  category
BaselineForecast            object
dtype: object